<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="C:\Users\ayman\OneDrive\سطح المكتب\CourseHub\Admin-Dashboard.png" Link="screenshots\Admin-Dashboard.png" />
    <Content Include="C:\Users\ayman\OneDrive\سطح المكتب\CourseHub\Course-Details.png" Link="screenshots\Course-Details.png" />
    <Content Include="C:\Users\ayman\OneDrive\سطح المكتب\CourseHub\Courses-Page.png" Link="screenshots\Courses-Page.png" />
    <Content Include="C:\Users\ayman\OneDrive\سطح المكتب\CourseHub\Courses-Page2.png" Link="screenshots\Courses-Page2.png" />
    <Content Include="C:\Users\ayman\OneDrive\سطح المكتب\CourseHub\Create-Course.png" Link="screenshots\Create-Course.png" />
    <Content Include="C:\Users\ayman\OneDrive\سطح المكتب\CourseHub\Instructor-Dashboard.png" Link="screenshots\Instructor-Dashboard.png" />
    <Content Include="C:\Users\ayman\OneDrive\سطح المكتب\CourseHub\Student-Dashboard.png" Link="screenshots\Student-Dashboard.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\ayman\OneDrive\سطح المكتب\README.md" Link="README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
